name: "Docs - Build and Deploy"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs  # Set working directory to 'docs'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Use a compatible Ruby version for Jekyll

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build --trace --verbose

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site  # Ensure this matches your Jekyll output directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2